Hw01.task01.hash table
maximumSHOT-HSE/Java-HW pull request #1
Opened 2019-01-21 20:24 UTC by maximumSHOT-HSE

Нужно ли добавлять файл `settings.gradle`? (на данный момент он добавлен)

2019-01-27 17:09 UTC, jzuken requested changes

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip
четвёртый gradle не умеет с java 11 работать

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +    private static final int NUM = 1; // numerator
вот только а если назвать переменную нормально, то и комментарий не нужен будет, правда?

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +    /*
если это джавадок, то тут должно быть две звёздочки

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +        free all data and set new capacity
и начинать описание вообще принято с заглавной буквы

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +            throw new IllegalArgumentException("original can not be null");
увидев это сообщение, всем будет очевидно, кто такой этот original?

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +        int position = key.hashCode() % capacity;
hashCode() вполне может отрицательное число вернуть

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +    /**
однострочные доки лучше так и оформлять одной строкой: `/** ... */`

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +     * */
бросаемые исключения тоже бы надо документировать

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +        if (size * (long)DENOM > capacity * (long)NUM) { // size > capacity * (NUM / DENOM). Calculations without loss of accuracy
после `(long)` тоже бы надо пробел

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/List.java
> +    public static class ListVertex {
а он кому-то ещё нужен за пределами этого списка?

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +        for (int i = 1;i <= 20;i++) {
пробелы

2019-01-27 17:09 UTC, jzuken commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +    void testGetPutWithNull() {
это всё лучше разбить на разные тесты

2019-01-27 20:12 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +    /*
Это не javadoc, а многострочный комментарий в коде

2019-01-27 20:15 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +        int position = key.hashCode() % capacity;
Ниже есть `if` на этот случай

2019-01-27 20:23 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/List.java
> +    public static class ListVertex {
ListVertex используется в классе HashTable, в таких случаях нужно писать вложенные классы (как здесь) или написать еще один класс вне List? Но по сути ListVertex не является самостоятельным классом и без List'а он никому не нужен. Есть ли стандартные структуры типа pair<T,P> в С++, чтобы не нужно было писать велосипед?

2019-01-27 20:40 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +    void testGetPutWithNull() {
Некоторые методы невозможно протестировать без использования других (например `get,put`), как быть в таких ситуациях? Или здесь конкретно про поведение с `null` ?

2019-01-28 08:42 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/List.java
> +    public static class ListVertex {
в таких случаях принято делать итератор, чтобы раскрывать детали реализации коллекции.
а стандартной пары в джаве, к сожалению, нет.

2019-01-28 08:43 UTC, jzuken commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +    void testGetPutWithNull() {
get и put понятно, но тут ещё куча разных исключений проверяется

2019-01-28 15:58 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip
fixed

2019-01-28 15:58 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +    private static final int NUM = 1; // numerator
fixed

2019-01-28 15:58 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +        free all data and set new capacity
fixed

2019-01-28 15:58 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +            throw new IllegalArgumentException("original can not be null");
fixed

2019-01-28 15:58 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +     * */
fixed

2019-01-28 15:59 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +        for (int i = 1;i <= 20;i++) {
fixed

2019-01-28 15:59 UTC, maximumSHOT-HSE commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +    void testGetPutWithNull() {
Разделил на два метода

2019-01-29 10:56 UTC, jzuken commented on hw01/task01.HashTable/src/test/java/ru/hse/surkov/hw01/HashTableTest.java
> +        for (int i = 1;i <= 20;i++) {
мне кажется, не стоит тут так явно отчитываться, я же потом всё равно смотрю новые коммиты. пишите, если есть, что сказать, по сути замечания

2019-02-11 10:03 UTC, jzuken requested changes

2019-02-11 10:03 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/HashTable.java
> +     * @throws IllegalArgumentException if ((key == null) or (value == null))
тут всё же текстом стоит писать, к тому же в вашем случае текстом бы ещё и короче получилось

2019-02-11 10:03 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/List.java
> +    public static class ListVertex {
мм, оно всё ещё public. если вам нужна просто пара, объявите её нормально отдельным классом и используйте везде. а узел листа для этого использовать не стоит
-0.5

2019-02-11 10:03 UTC, jzuken commented on hw01/task01.HashTable/src/main/java/ru/hse/surkov/hw01/List.java
> +        list = new ListVertex[listCapacity];
лучше всё это инициализировать сразу при объявлении

2019-02-28 10:00 UTC, merged