Hw08.task01.cannon
maximumSHOT-HSE/Java-HW pull request #10
Opened 2019-05-19 17:52 UTC by maximumSHOT-HSE

2019-05-19 17:52 UTC, maximumSHOT-HSE commented
Чтобы выбрать снаряд определнной массы, нажмите клавиши "1", "2" или "3"

2019-05-31 13:23 UTC, RamSaw commented
> Чтобы выбрать снаряд определнной массы, нажмите клавиши "1", "2" или "3"

лучше это в игре написать, а не в PR

2019-05-31 14:01 UTC, RamSaw requested changes
@maximumSHOT-HSE проверил, жду исправлений или контраргументов. После того, как исправите позовите меня через собаку. 
Респект за тесты и +1 балл.

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/build.gradle
> +mainClassName = 'ru.hse.surkov.hw08.Main'
jar не запускается

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/settings.gradle
> +rootProject.name = 'hw08.task01.cannon'
Игровой процесс хороший, только выведите все же пожалуста инфу, как поменять оружеие.
Еще пока я играл, вывалилось мне в терминал:
`(java:32064): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`
У Вашей коллеги тоже такое случилось, можете с кооперироваться в поисках бага  :)

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Cannon.java
> +            ys[i] = gameState.getFieldHeight() - vertices.get(i).getY();
вообще можно выделить в отделльный метод, типа transformToScreenCoordinates

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/GameLoop.java
> +        double deltaTime = (currentNanoTime - previousNanoTime) * 1e-3;
почему 1e-3? выделите в метод, объясняющий что он делает.

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/GameState.java
> +     * */
пробел

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Landscape.java
> +        return fieldHeight * 2;
это что за значение такое? мб исключение кидать, такого же не должно происходить.

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Main.java
> +                        .getDefaultToolkit()
я думаю лучше читается если не переносить на новую строчку

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/PhysicsEngine.java
> +                            -RATIO_DELTA_ANGLE_PER_TOUCH * Math.PI / 2);
зачем перенос строчки делать, выглядит же странно, нет?

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Vector2D.java
> +public class Vector2D {
в JavaFX есть Point2D, она вам чем-то не подошла или вы про нее не знали просто?

2019-05-31 14:01 UTC, RamSaw commented on hw08/task01.cannon/src/test/java/ru/hse/surkov/hw08/LandscapeTest.java
> +    void testOutOfBandsX() {
bounds?

2019-05-31 14:54 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Cannon.java
> +            ys[i] = gameState.getFieldHeight() - vertices.get(i).getY();
Не понятно, на сколько это оправдано ради одной строчки.

2019-05-31 15:04 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Landscape.java
> +        return fieldHeight * 2;
Исключения дорог, вместо этого можно считать, что по бокам очень высокие горы.

2019-05-31 15:07 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/PhysicsEngine.java
> +                            -RATIO_DELTA_ANGLE_PER_TOUCH * Math.PI / 2);
Иначе строчки очень длинные.

2019-05-31 15:07 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Vector2D.java
> +public class Vector2D {
Не знал.

2019-06-03 14:22 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Main.java
> +                        .getDefaultToolkit()
Действительно.

2019-06-03 14:24 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/GameState.java
> +     * */
Я так поянл, что тут речь про пробел между звездочками, а как в принципе правильно писать звездочки в javadoc'ах. просто в некоторых библиотках пишут
`
/**
*/
`
А IDEA например автодополняет до 
`
/**
* */
`

2019-06-03 14:29 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/settings.gradle
> +rootProject.name = 'hw08.task01.cannon'
Пытался найти решени в интернете, но вышло починить этот warning, возможно дело в вызове `graphicsContext = canvas.getGraphicsContext2D();`, но единственное, что удалось выяснить, что это ругается не мой код. И ругается непонятно, на что.

2019-06-03 14:31 UTC, maximumSHOT-HSE commented on hw08/task01.cannon/build.gradle
> +mainClassName = 'ru.hse.surkov.hw08.Main'
Сначала была ошибка, связанная с тем, что не прописал в `build.gradle` класс для таски `jar`, однако руками не получается запустить `jar`-ник, Что-то `javafx` не дружит с `Java 11`. Есть какой-нибудь способ запустить `jar`-ник имея на руках `javafx 11 sdk`?

2019-06-03 14:32 UTC, maximumSHOT-HSE commented
@RamSaw partial fix

2019-06-04 12:37 UTC, RamSaw commented on hw08/task01.cannon/build.gradle
> +mainClassName = 'ru.hse.surkov.hw08.Main'
там надо прописать пути до javaFX. То что вы в gradle изменили будет работать, если прописать эти пути, так что все ок.

2019-06-04 12:38 UTC, RamSaw commented on hw08/task01.cannon/settings.gradle
> +rootProject.name = 'hw08.task01.cannon'
У Ваших сокурсников некоторых тоже такая ошибка есть, где-то еще 2 человек. Но мне тоже кажется, что это баг JavaFX какой-то.

2019-06-04 12:40 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/Cannon.java
> +            ys[i] = gameState.getFieldHeight() - vertices.get(i).getY();
их я насчитал две, но да ладно. Вообще даже если и одна, выделяя такой метод читающий сразу поймет, что у вас в коде и на экране разные координаты. А это может быть не совсем очевидно для читающего код, особенно если он никогда не работал с графикой.

2019-06-04 12:43 UTC, RamSaw commented on hw08/task01.cannon/src/main/java/ru/hse/surkov/hw08/GameState.java
> +     * */
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf
одна звездочка должна быть в конце. Не думаю, что это прям критично, но вот пробел бросился мне в глаза сразу, уж очень он выделяется здесь :)

2019-06-04 12:49 UTC, RamSaw approved these changes
@maximumSHOT-HSE почему partial fix? вы вроде все пофиксили и меня все устраивает.
@jzuken

2019-06-06 07:40 UTC, merged