hw09.task01.MyJUnit
maximumSHOT-HSE/Java-HW pull request #11
Opened 2019-05-27 12:48 UTC by maximumSHOT-HSE

2019-06-08 07:04 UTC, jzuken requested changes

2019-06-08 07:04 UTC, jzuken commented on hw09/task01.MyJUnit/src/main/java/hse/surkov/hw09/MyJUnit.java
> +        var beforeClassMethods = retrieveMethodsByAnnotation(methods, BeforeClass.class);
а вот обычный junit требует, чтобы эти методы были статические. давайте тоже так сделаем

2019-06-08 07:04 UTC, jzuken commented on hw09/task01.MyJUnit/src/main/java/hse/surkov/hw09/MyJUnit.java
> +    @NotNull public static List<TestData> executeTests(@NotNull Class<?> clazz) throws
не нашёл, где время выполнения тестов считается
-1

2019-06-08 07:04 UTC, jzuken commented on hw09/task01.MyJUnit/src/test/java/hse/surkov/hw09/IgnoreClassTest.java
> +public class IgnoreClassTest {
я бы положил эти классы в отдельный пакет тут, чтобы не мешались

2019-06-10 00:52 UTC, maximumSHOT-HSE commented on hw09/task01.MyJUnit/src/main/java/hse/surkov/hw09/MyJUnit.java
> +        var beforeClassMethods = retrieveMethodsByAnnotation(methods, BeforeClass.class);
Хорошо, но это было не очевидно.

2019-06-10 07:42 UTC, jzuken commented on hw09/task01.MyJUnit/src/main/java/hse/surkov/hw09/MyJUnit.java
> +        var beforeClassMethods = retrieveMethodsByAnnotation(methods, BeforeClass.class);
ну так я и баллов за это не снимаю

2019-06-10 08:40 UTC, merged