Hw10.task01.ftpgui
maximumSHOT-HSE/Java-HW pull request #12
Opened 2019-06-04 23:44 UTC by maximumSHOT-HSE

Contributors:
@maximumSHOT-HSE 
@anstkras

2019-06-09 11:44 UTC, RamSaw requested changes
@maximumSHOT-HSE проверил.
-1 за неполную функциональность: невозможность запуска сервера с помощью gradle и невозможность гулять по всем директориям.

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/build.gradle
> +mainClassName = 'ru.hse.hw10.client.gui.ClientGUIIntro'
сервер не могу запустить

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +
не надо пропускать строчку, пожалуйста

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +    private static final int PORT = 9999;
не надо хардкодить порт сервера, он может быть занят

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/settings.gradle
> +rootProject.name = 'hw10.task01.FTPGUI'
не могу сделать back, даже если я не в самом корне своего диска.
он запускается, будто корень это директория откуда я запустил программу.
download непонятно куда идет. Скажите куда, я удалю, а то наверняка он сохранился не туда, куда я хочу.

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +            socket.connect(InetAddress.getByName("8.8.8.8"), PORT);
в константу класса

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +            socket.connect(InetAddress.getByName("8.8.8.8"), PORT);
а зачем это делать кстати?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +                // TODO handle me
ну вот сделайте TODO

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +                // TODO handle me
и везде ниже тоже

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +        return file.exists() ? file : null;
вроде у Path есть метод toFile()

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +                Server.LOGGER.info(child.getName() + " is dir = " + child.isDirectory());
выделите в отдельный метод
логирование особо в логику не входит

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +            dataOutputStream.writeInt(Objects.requireNonNull(childFiles).length);
выше вы делает if на childFiles, а здесь собираетесь бросить NPE, как-то не консистентно.

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +        buffer.putInt(remainingBytesNumber);
зачем два раза туда пихать?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/OutputWriter.java
> +        if (data.isFinished()) {
очень трудно понимать код, когда isFinished не просто проверяет, а еще и что-то делает

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/OutputWriter.java
> +            if (Server.select(outputWriterSelector) == 0) {
не очень понятно, что этот код делает. Если это какая-то проверка, то надо создать такой метод, который будет возращать boolean

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        outputWriterThread = new Thread(new OutputWriter(outputWriterSelector));
а ему outputWriterSelectorLock не нужен?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        acceptReceiverThread.interrupt();
'+ join

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        } catch (IOException e) {
ignored

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/Client.java
> +        try (SocketChannel socketChannel = SocketChannel.open(address)) {
а разве поддерживать соединения постоянно нельзя?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/Client.java
> +        byte[] fileContent = dataInputStream.readAllBytes();
если файл очень большой, то будут проблемы

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUI.java
> +        filesListView = new ListView<>(files);
лучше разбить этот большой файл на методы

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUI.java
> +                    Files.createDirectories(path.getParent());
ну визуально на localhost'e так трудно тестировать, да и порой мб не очень удобно. Вдруг  у меня есть такой же файл, но я не хочу чтобы вы его удаляли.

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUIIntro.java
> +public class ClientGUIIntro extends Application {
Intro?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/FileCellFactory.java
> +        return new FileCell();
а где здесь listView используется?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/FileCellFactory.java
> +        return new FileCell();
странная архитектура какая-то
почему фабрика является колбэком?

2019-06-09 11:44 UTC, RamSaw commented on hw10/task01.FTPGUI/src/test/java/ru/hse/hw10/ServerTest.java
> +class ServerTest {
это тестирование не сервера, а сервера и клиента вместе.

2019-06-09 11:44 UTC, RamSaw commented
@maximumSHOT-HSE @anstkras зачем вы кстати на селекторах писали? Кажется, от этого только больше кода получается, который сложнее понимать.

2019-06-11 11:10 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/build.gradle
> +mainClassName = 'ru.hse.hw10.client.gui.ClientGUIIntro'
Fixed, `./gradlew runServer --args <port>`

2019-06-11 11:11 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +
Хорошо. Это есть в каком-нибудь сталгайде?

2019-06-11 11:15 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/settings.gradle
> +rootProject.name = 'hw10.task01.FTPGUI'
Что значит в корне вашего диска? Сервер не позволяет ходить выше того места, откуда запустился сервер в целях безопасности. Файл сохраняется в то место, откуда был запущен клиент. Если файл с таким именем уже был, то он перезапишется.

2019-06-11 11:25 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +        buffer.putInt(remainingBytesNumber);
Издержки протокола передачи данных. Сначала передается размер пакета, затем сам пакет. Это нужно для того, чтобы удобно обрабатывать -1 в случае, когда файла не существует.

2019-06-11 11:39 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/OutputWriter.java
> +        if (data.isFinished()) {
Поделил на два метода.

2019-06-11 11:42 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/OutputWriter.java
> +            if (Server.select(outputWriterSelector) == 0) {
Это метод, который возвращает количество готовых каналов. Как и в Selector'e, только он еще и IO problems обрабатывает (см. javadocs)

2019-06-11 11:46 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        outputWriterThread = new Thread(new OutputWriter(outputWriterSelector));
Нет, т.к. lock'и нужны только для регистрации в селекторе.

2019-06-11 11:50 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        acceptReceiverThread.interrupt();
Зачем делать `join`?

2019-06-11 11:51 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/Client.java
> +        try (SocketChannel socketChannel = SocketChannel.open(address)) {
У нас на каждый запрос создается новое соединение (это больше для упрощения задачи, т.к. не хочется возиться с кучей запросов через один канал).

2019-06-11 11:53 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/test/java/ru/hse/hw10/ServerTest.java
> +class ServerTest {
А как инаxе тестировать два объекта, которые умеют взаимодествовать только друг с другом?

2019-06-11 11:53 UTC, maximumSHOT-HSE commented
По заданию нужно было написать сервер с неблокирующей архитектурой.

2019-06-11 11:55 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +    private static final int PORT = 9999;
Fixed

2019-06-11 11:56 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +            socket.connect(InetAddress.getByName("8.8.8.8"), PORT);
Removed)

2019-06-11 11:56 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +                // TODO handle me
fixed

2019-06-11 11:56 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/Server.java
> +        } catch (IOException e) {
fixed

2019-06-11 13:01 UTC, anstkras commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +                Server.LOGGER.info(child.getName() + " is dir = " + child.isDirectory());
fixed

2019-06-11 13:09 UTC, anstkras commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/FileCellFactory.java
> +        return new FileCell();
`ListView` используется для отображения списка файлов.
Архитектура странная у JavaFX :)
Метод у `ListView`, который позволяет устанавливать свою CellFactory, имеет следующую сигнатуру ```public final void setCellFactory(Callback<ListView<T>, ListCell<T>> value)```

2019-06-11 13:10 UTC, anstkras commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUIIntro.java
> +public class ClientGUIIntro extends Application {
fixed

2019-06-11 13:35 UTC, anstkras commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUI.java
> +        filesListView = new ListView<>(files);
fixed

2019-06-11 13:40 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +        return file.exists() ? file : null;
Здесь path - это объект класса `String`.

2019-06-11 13:46 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +        return file.exists() ? file : null;
Изменил название переменной для большей ясности

2019-06-11 13:48 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/ClientData.java
> +            dataOutputStream.writeInt(Objects.requireNonNull(childFiles).length);
Убрал `if`

2019-06-11 16:17 UTC, anstkras commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/gui/ClientGUI.java
> +                    Files.createDirectories(path.getParent());
Теперь пользователь может выбирать директорию для сохранения файла. Если файл с таким именем уже существует в этой директории, будет показано сообщение об этом.

2019-06-11 16:20 UTC, anstkras commented on hw10/task01.FTPGUI/settings.gradle
> +rootProject.name = 'hw10.task01.FTPGUI'
Теперь файл сохранится в выбранную с помощью `DirectoryChooser` директорию. Если файл с таким именем уже есть, покажется сообщение об этом.

2019-06-11 17:31 UTC, maximumSHOT-HSE commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/client/Client.java
> +        byte[] fileContent = dataInputStream.readAllBytes();
Fixed. Теперь файл в 1G скачивается примерно за минут 20 напрямую с сервера.

2019-06-11 17:55 UTC, maximumSHOT-HSE commented
@RamSaw fixed

2019-06-13 10:58 UTC, RamSaw approved these changes
@maximumSHOT-HSE @anstkras все ок
@jzuken

2019-06-13 10:58 UTC, RamSaw commented on hw10/task01.FTPGUI/src/main/java/ru/hse/hw10/AcceptReceiver.java
> +
Ну а зачем ее пропускать. Я это у многих вижу и не понимаю, зачем это делать. Читаемость от этого не изменяется нисколько.

2019-06-13 10:58 UTC, RamSaw commented on hw10/task01.FTPGUI/src/test/java/ru/hse/hw10/ServerTest.java
> +class ServerTest {
моки. Но я не про это говорил, я про то, что тест ClientServerTest лучше назвать.

2019-06-13 12:16 UTC, merged