Hw02.task01.trie
maximumSHOT-HSE/Java-HW pull request #2
Opened 2019-01-29 17:53 UTC by maximumSHOT-HSE

Когда всё-таки нужно использовать `var`? Всегда или когда имя типа слишком длинное?

2019-02-13 08:44 UTC, jzuken requested changes

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Serializable.java
> +public interface Serializable {
тут тоже можно было бы написать комментарий

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Serializable.java
> +     * In case of in == null nothing will happen.
слово is вместо знака равенства бы заняло ровно столько же символов, но при этом это был бы нормальный английский текст

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        if (element == null) {
ну, строго говоря, это отдельная ситуация, и просто заметать её под ковёр не стоит

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        if (out == null) {
как и тут

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        private int cntLeafsInSubTree;
не надо использовать сокращения в именах. этому конкретному полю можно придумать более короткое и ёмкое имя, типа childrenCount или что-то ещё
-0.5

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        private HashMap<Character, Node> arc;
что за arc? и это коллекция, кстати, что подразумевает множественное число
-0.5

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +            arc = new HashMap<>();
лучше инициализировать при объявлении

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +         * <how many arcs: int>
тут тоже экономите на описаниях? документация должна быть понятной, напрягитесь уж, напишите ещё пару слов. 

и что метод рекурсивный, кстати, тут вообще никому не интересно

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +            for (int iter = 0; iter < size; iter++) {
опять ненужное сокращение. писали бы уж просто i тогда, ра з оно вам всё равно не надо

2019-02-13 08:44 UTC, jzuken commented on hw02/task01.Trie/src/test/java/ru/hse/surkov/hw02/TrieTest.java
> +        for (int cntSymbols = 0; cntSymbols < 100; cntSymbols++, c++) {
:(

2019-02-13 08:44 UTC, jzuken commented
var стоит использовать всегда, когда тип очевиден из правой части

2019-02-19 16:56 UTC, maximumSHOT-HSE commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        private HashMap<Character, Node> arc;
По поводу множественного числа согласен, но arc -- дуга (англ.), довольно часто используемое имя в подобных структурах (похожая альтернатива edges).

2019-02-19 17:00 UTC, maximumSHOT-HSE commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +            arc = new HashMap<>();
Получается, что конструктор по умолчанию вообще не нужен? Но если в классе есть другой конструктор, то default'ный не генерируется и приходится писать 
пустой Node() { }, если следовать подходу "инициализировать при объявлении". Как лучше делать, если несколько конструкторов?

2019-03-07 11:52 UTC, jzuken commented
конфликт с мастером

2019-03-07 11:57 UTC, jzuken requested changes

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +     * false -- if there was or element == null
нет, это плохое решение. а как вызывающий код узнает, был ли там элемент или ему вернулся false потому, что null передали? null в качестве аргумента это скорее проблема, чем штатная ситуация, поэтому надо кидать исключение. я ж писал про это 
-1

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        private int subtreeLeafsCount;
`leaves` тогда уж

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        Node() {
модификаторы видимости потерялись

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +            if (in == null) {
а если формат неправильный?

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +                incLeafsCounter(+1);
а есть какой-то тайный смысл передавать сюда +1 вместо 1?

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +            for (var elem : arcsToChildren.entrySet()) {
не надо так сокращать, пожалуйста
-0.5

2019-03-07 11:57 UTC, jzuken commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +        private void incLeafsCounter(int diff) {
и так тоже сокращать не надо

2019-03-10 14:01 UTC, maximumSHOT-HSE commented on hw02/task01.Trie/src/main/java/ru/hse/surkov/hw02/Trie.java
> +                incLeafsCounter(+1);
Тайного смысла нет, то это подчеркивает тот факт, что происходит именно увеличение.

2019-03-13 14:21 UTC, merged