Hw03.task01.my tree set
maximumSHOT-HSE/Java-HW pull request #3
Opened 2019-02-09 23:02 UTC by maximumSHOT-HSE

В похожих заданиях какие из открытых методов нужно тестировать, т.е. нужно ли тестировать кучу методов из классов или интерфейсов, от которых наследуются мои (но не укаказаны в условии)?

2019-02-27 14:52 UTC, jzuken commented
надо тестировать всё, не только то, что в условии указано

2019-02-28 09:27 UTC, jzuken requested changes

2019-02-28 09:27 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Treap.java
> +    private class DataHolder {
такие подклассы лучше уносить в конец объемлющего

2019-02-28 09:27 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Treap.java
> +            root = null;
ну это за вас вообще виртуальная машина делает

2019-02-28 09:27 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Treap.java
> +        DataHolder() {
package level?

2019-02-28 09:27 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Treap.java
> +            return parent != null && (parent.left == this);
как-то у вас интересно тут скобки стоят

2019-02-28 09:27 UTC, jzuken commented on hw03/task01.MyTreeSet/src/test/java/ru/hse/surkov/hw03/TreapTest.java
> +//                assertThrows(IllegalArgumentException.class, () -> set.remove(null));
так у меня и в IDE эти тесты не проходят:

org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> 
Expected :<java.lang.IllegalArgumentException> 
Actual   :<java.lang.NullPointerException>

2019-03-13 13:41 UTC, jzuken requested changes

2019-03-13 13:41 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Pair.java
> +    public F first;
не, публичных полей не бывает. хотите делать полноценный класс пары -- на здоровье, но не в таком виде
-0.5

2019-03-13 17:58 UTC, maximumSHOT-HSE commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Pair.java
> +    public F first;
Fixed, а почему сейчас <= 10.5, хотя всего можно получить 12, но я заметил лишь один -0.5?

2019-03-13 19:28 UTC, jzuken commented on hw03/task01.MyTreeSet/src/main/java/ru/hse/surkov/hw03/Pair.java
> +    public F first;
а это за прошлую проверку стояло. видимо, за непроходящие тесты, я там забыл отметить

2019-03-16 14:38 UTC, merged